### ISSUE TITLE
Harmony cannot patch other Assemblies loaded in another AppDomains

### ISSUE THREAD

**Issue by albgen** [pardeike/Harmony#322]
hi,

I don't know if it is a feature request or a bug but here it is my scenario which is not working.

**Describe the bug**
I have 2 c# executable files. First one, lets say A is the target, Second one B, is the injector.
The purpose is to inject the dll and start harmony to patch DateTime.Now used in A.

I used another library and the injection works perfectly, even the starting code for harmony is working but the problem is that i cannot get the Assemblies of Executable A because they are in another AppDomain so i cannot patch them.

The question is: Is it possible for Harmony to patch all assemblies in other AppDpomains?

**Comment by pardeike** [comment]
Handling state across different AppDomains requires serialization and intricate knowledge of the data types. As such it is very hard to create a general and fast solution to deal with this from outside the affected code base. 

This means that this feature will stay a #wontfix for the foreseeable future.

**Comment by albgen** [comment]
Kindly can you make a simple example i case i know the datatype?

**Comment by pardeike** [comment]
That’s not what I meant. All access across AppDomains must happen serialized. Which means a substantial rewrite of Harmony. It’s not a matter of what you can do but what Harmony must be able to do.

**Comment by pardeike** [comment]
Even simple access of object is super complicated. See https://stackoverflow.com/questions/2206961/sharing-data-between-appdomains for a bit more information and that applies mostly if you are in control of both sides (which in case of Harmony you are not).

**Comment by albgen** [comment]
i have found some code snippets that is returning appdomain's assemblies for all AppDomains in a process but of course it does not work because the code of harmony usually uses AppDomain.Current.

I will try to change with some hardcoded values to see id it does work...

**Comment by pardeike** [comment]
Manual patching (as described at the end of https://harmony.pardeike.net/articles/intro.html) does not use AppDomain but I guess you will run into type cast exception.

**Comment by albgen** [comment]
> Manual patching (as described at the end of https://harmony.pardeike.net/articles/intro.html) does not use AppDomain but I guess you will run into type cast exception.

does not work and does not even throw any exception at all. Seems it has patched but actually does not work..

**Comment by pardeike** [comment]
And it was never designed to do it. Hence the #wontfix - at least for the foreseeable future.

**Comment by pardeike** [comment]
Fixed in master

**Comment by albgen** [comment]
Fixed in master patching on other appdomain?

**Comment by pardeike** [comment]
You forgot the #wontfix label. I just documented the limitation.

**Comment by Albeoris** [comment]
Eh... I tryed to use it to solve problems with stripped DLLs where is no "GetMethodBody" and other methods that needed to make harmony work properly. :(
